trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  city: ''
  
parameters:
  - name: value
    displayName: City
    default: 'thane'
    values:
      - 'thane'
      - 'chennai'
      - 'ladakh'
      - 'delhi'

steps:
- task: NodeTool@0
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm start
  displayName: 'npm build'

- script: |
    node server.js $(value)
  displayName: 'npm run'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: weatherApp
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish pipeline artifact'
